export const RoutePaths = {
  HOMEPAGE: '/',
  SIGNIN: '/signin',
  SIGNUP: '/signup',
  PROFILE: '/profile',
  BROWSECARS: '/browse-vehicles',
  BROWSEPARTS: '/browse-parts',
  BROWSE_PART_LISTINGS: '/browse-part-listings/:partId',
  PART_LISTING_DETAIL: '/listings/part/:listingId',
  SELLITEMS: '/sell-items',
  BROWSE_VEHICLE_LISTINGS: '/browse-vehicle-listings/:vehicleId',
  LISTING_DETAIL: '/listings/vehicle/:listingId',
  SELLERREGISTRATION: '/seller-registration',
  REVIEWS: '/businesses/:id/reviews',
  BUSINESSES: '/businesses',
  BUSINESS_DETAILS: '/businesses/:id',
};
